<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJVW4YPJ\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJVW4YPJ/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerJVW4YPJ.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerJVW4YPJ\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerJVW4YPJ\appAppKernelProdContainer([
    'container.build_hash' => 'JVW4YPJ',
    'container.build_id' => '9b85aa3f',
    'container.build_time' => 1705973030,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJVW4YPJ');
