<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG3lqk6j\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG3lqk6j/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerG3lqk6j.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerG3lqk6j\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerG3lqk6j\appAppKernelProdContainer([
    'container.build_hash' => 'G3lqk6j',
    'container.build_id' => 'fba71985',
    'container.build_time' => 1747436092,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG3lqk6j');
